<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[onStart]]>
    </line>
    <line>
      <![CDATA[onTestStart]]>
    </line>
    <line>
      <![CDATA[main2]]>
    </line>
    <line>
      <![CDATA[onTestFailures]]>
    </line>
    <line>
      <![CDATA[onTestStart]]>
    </line>
    <line>
      <![CDATA[main1]]>
    </line>
    <line>
      <![CDATA[onTestSuccess]]>
    </line>
    <line>
      <![CDATA[onTestStart]]>
    </line>
    <line>
      <![CDATA[onTestSkipped]]>
    </line>
    <line>
      <![CDATA[onFinish]]>
    </line>
  </reporter-output>
  <suite started-at="2025-01-03T16:06:28 IST" name="Default suite" finished-at="2025-01-03T16:06:28 IST" duration-ms="104">
    <groups>
    </groups>
    <test started-at="2025-01-03T16:06:28 IST" name="Default test" finished-at="2025-01-03T16:06:28 IST" duration-ms="104">
      <class name="ListenerInterface.TestCase1">
        <test-method signature="main2()[pri:0, instance:ListenerInterface.TestCase1@7133da86]" started-at="2025-01-03T16:06:28 IST" name="main2" finished-at="2025-01-03T16:06:28 IST" duration-ms="24" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Selenium] but found [java]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Selenium] but found [java]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at ListenerInterface.TestCase1.main2(TestCase1.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[onTestStart]]>
            </line>
            <line>
              <![CDATA[main2]]>
            </line>
            <line>
              <![CDATA[onTestFailures]]>
            </line>
          </reporter-output>
        </test-method> <!-- main2 -->
        <test-method signature="main1()[pri:0, instance:ListenerInterface.TestCase1@7133da86]" started-at="2025-01-03T16:06:28 IST" name="main1" finished-at="2025-01-03T16:06:28 IST" duration-ms="3" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[onTestStart]]>
            </line>
            <line>
              <![CDATA[main1]]>
            </line>
            <line>
              <![CDATA[onTestSuccess]]>
            </line>
          </reporter-output>
        </test-method> <!-- main1 -->
        <test-method signature="main3()[pri:0, instance:ListenerInterface.TestCase1@7133da86]" started-at="2025-01-03T16:06:28 IST" name="main3" finished-at="2025-01-03T16:06:28 IST" depends-on-methods="ListenerInterface.TestCase1.main2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase1.main3()[pri:0, instance:ListenerInterface.TestCase1@7133da86] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase1.main3()[pri:0, instance:ListenerInterface.TestCase1@7133da86] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[onTestSkipped]]>
            </line>
            <line>
              <![CDATA[onFinish]]>
            </line>
          </reporter-output>
        </test-method> <!-- main3 -->
      </class> <!-- ListenerInterface.TestCase1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
